# Use an official Nginx image as the base image
FROM nginx

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration file into the container
COPY nginx/nginx.conf /etc/nginx/conf.d/

# Copy the built Angular app to the appropriate location in the container
COPY dist/frontend/browser /usr/share/nginx/html

# Expose port 80 for the Nginx server
EXPOSE 80

# Start the Nginx server when the container starts
CMD ["nginx", "-g", "daemon off;"]